### ISSUE TITLE
Site feature request: make it easier to read all tips from start to finish

### ISSUE THREAD

**Issue by caspark** [umaar/dev-tips#18]
I just found your site and there are a whole bunch of awesome tricks there, so naturally I want to gorge on them. But it's a little painful to go through them all because when I go back to the list of tips then I've lost my spot in the list.

If each page had a next & previous link, it would make browsing through tips much easier.

Or alternatively, `a:visited { color: red; }` or similar - that's what I've done in the meantime.

**Comment by umaar** [comment]
Good idea: I'll get this done within a week.

**Comment by umaar** [comment]
Done.

**Comment by badarshahzad** [comment]
:+1: interesting @umaar
